# Generated by Django 5.2 on 2025-04-23 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingslot',
            name='unique_booking_per_slot_time',
        ),
        migrations.AddConstraint(
            model_name='bookingslot',
            constraint=models.UniqueConstraint(fields=('user', 'slot', 'slot_time'), name='unique_booking_per_slot_time'),
        ),
    ]
