-- local confirmedKey = KEYS[1]
-- local waitingKey = KEYS[2]

-- local userId = ARGV[1]
-- local capacity = tonumber(ARGV[2])

-- local confirmedCount = redis.call(
--     "LLEN",
--     confirmedKey
-- )

-- if confirmedCount < capacity then

--     redis.call(
--         "RPUSH",
--         confirmedKey,
--         userId
--     )

--     return "CONFIRMED"

-- end

-- redis.call(
--     "RPUSH",
--     waitingKey,
--     userId
-- )

-- return "WAITING"


----------------------------------------------------------------------------------------------------------------------------------

-- booking.lua

-- KEYS[1]
-- qskip:queue_entries_of_q<queueId>_is_confirmed

-- KEYS[2]
-- qskip:queue_entries_of_q<queueId>_is_waiting

-- ARGV[1] = user_id
-- ARGV[2] = capacity
-- ARGV[3] = req_at (epoch milliseconds from frontend)
-- ARGV[4] = booked_at (epoch milliseconds generated by backend)

local confirmedKey = KEYS[1]
local waitingKey = KEYS[2]

local userId = tostring(ARGV[1])
local capacity = tonumber(ARGV[2])
local reqAt = tostring(ARGV[3])
local bookedAt = tostring(ARGV[4])

--------------------------------------------------
-- DOUBLE BOOKING CHECK : CONFIRMED
--------------------------------------------------

local confirmedEntries = redis.call(
    "LRANGE",
    confirmedKey,
    0,
    -1
)

for i = 1, #confirmedEntries do

    local entry = confirmedEntries[i]

    if string.find(entry, '"user_id":"' .. userId .. '"', 1, true) then
 
        return {
            "ALREADY_BOOKED",
            "CONFIRMED"
        }

    end

end

--------------------------------------------------
-- DOUBLE BOOKING CHECK : WAITING
--------------------------------------------------

local waitingEntries = redis.call(
    "LRANGE",
    waitingKey,
    0,
    -1
)

for i = 1, #waitingEntries do

    local entry = waitingEntries[i]

    if string.find(entry, '"user_id":"' .. userId .. '"', 1, true) then

        return {
            "ALREADY_BOOKED",
            "WAITING"
        }

    end

end

--------------------------------------------------
-- CONFIRMED COUNT
--------------------------------------------------

local confirmedCount = redis.call(
    "LLEN",
    confirmedKey
)

--------------------------------------------------
-- CONFIRMED
--------------------------------------------------

if confirmedCount < capacity then

    local positionNo = confirmedCount + 1

    local payload =
        '{"user_id":"' .. userId ..
        '","position_no":"' .. positionNo ..
        '","booked_at":"' .. bookedAt ..
        '","req_at":"' .. reqAt ..
        '"}'

    redis.call(
        "RPUSH",
        confirmedKey,
        payload
    )

    return {
        "CONFIRMED",
        tostring(positionNo),
        bookedAt
    }

end

--------------------------------------------------
-- WAITING
--------------------------------------------------

local waitingCount = redis.call(
    "LLEN",
    waitingKey
)

local positionNo = waitingCount + 1

local payload =
    '{"user_id":"' .. userId ..
    '","position_no":"' .. positionNo ..
    '","booked_at":"' .. bookedAt ..
    '","req_at":"' .. reqAt ..
    '"}'

redis.call(
    "RPUSH",
    waitingKey,
    payload
)

return {
    "WAITING",
    tostring(positionNo),
    bookedAt
}